name: Publish BiGG to BioSimulations

on:
  schedule:
    - cron: '0 1 * * 0' # weekly at 1:00 am on Sundays

  workflow_dispatch:
    inputs:
      updateCombineArchives:
        description: 'Whether to overwrite existing COMBINE/OMEX archives: "0" (default) or "1"'
        required: false
        default: '0'
      updateSimulationRuns:
        description: 'Whether to overwrite existing simulation runs: "0" (default) or "1"'
        required: false
        default: '0'

jobs:
  publish:
    name: Publish BiGG to BioSimulations
    runs-on: ubuntu-latest
    env:
      ENTREZ_EMAIL: ${{ secrets.ENTREZ_EMAIL }}
      GRB_WLSACCESSID: ${{ secrets.GRB_WLSACCESSID }}
      GRB_WLSSECRET: ${{ secrets.GRB_WLSSECRET }}
      GRB_LICENSEID: ${{ secrets.GRB_LICENSEID }}
      BIOSIMULATIONS_API_CLIENT_ID: ${{ secrets.BIOSIMULATIONS_API_CLIENT_ID }}
      BIOSIMULATIONS_API_CLIENT_SECRET: ${{ secrets.BIOSIMULATIONS_API_CLIENT_SECRET }}
      BUCKET_ENDPOINT_DOMAIN_PORT: 4443
      BUCKET_ENDPOINT: https://localhost:4443
      BUCKET_PUBLIC_ENDPOINT: ${{ secrets.BUCKET_PUBLIC_ENDPOINT }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      BUCKET_PREFIX: ${{ secrets.BUCKET_PREFIX }}
      BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
      BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: dev

      # Install requirements
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.optional.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      # install package
      - name: Install the package
        run: python -m pip install .

      # Setup SSH connection for S3 bucket
      - name: Set up SSH connection for S3 bucket
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.BUCKET_SSH_KEY }}" > ~/.ssh/id_bucket_ssh
          chmod 600 ~/.ssh/id_bucket_ssh
          ssh-keyscan -H ${{ secrets.BUCKET_SSH_HOST }} >> ~/.ssh/known_hosts

      # Publish models to BioSimulations
      - name: Publish models to BioSimulations
        run: |
          ssh \
            -i ~/.ssh/id_bucket_ssh \
            -L ${BUCKET_ENDPOINT_DOMAIN_PORT}:${{ secrets.BUCKET_ENDPOINT }}:443 \
            -fNT \
            ${{ secrets.BUCKET_SSH_USERNAME }}@${{ secrets.BUCKET_SSH_HOST }}

          if [ "${{ github.event.inputs.updateCombineArchives }}" = "1" ]; then
            args="--update-combine-archives --update-simulation-runs"
          else
            if [ "${{ github.event.inputs.updateSimulationRuns }}" = "1" ]; then
              args="--update-simulation-runs"
            else
              args=""
            fi
          fi

          biosimulations-bigg publish $args

      # Push compiled projects
      - id: commit-projects
        name: Commit the compiled projects
        run: |
          git config --local user.email "biosimulations.daemon@gmail.com"
          git config --local user.name "biosimulationsdaemon"
          git config pull.rebase false
          git stash
          git pull
          set +e
          git stash pop
          git add biosimulations_bigg/source
          git lfs track biosimulations_bigg/source/thumbnails/**/*.tar.gz
          git add -f biosimulations_bigg/source/thumbnails/**/*.tar.gz
          git add -f biosimulations_bigg/source/thumbnails/**/**/*.jpg
          git add -f biosimulations_bigg/source/thumbnails/**/**/*.nxml
          git add biosimulations_bigg/final
          git commit -m "Updated compiled projects [skip ci]"
          if [[ $? = 0 ]]; then
            changed=1
          else
            changed=0
          fi
          echo "::set-output name=changed::$changed"

      - name: Push the compiled projects
        if: steps.commit-projects.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
