name: Verify that projects were successfully published to BioSimulations

on:
  schedule:
    - cron: '0 7 * * 0' # weekly at 7:00 am on Sundays

  workflow_dispatch:

jobs:
  verify:
    name: Verify that projects were successfully published to BioSimulations
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: dev
          lfs: true

      # Install requirements
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.optional.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      # install package
      - name: Install the package
        run: python -m pip install -e .

      # Verify that each project was successfully published
      - name: Verify that each project was successfully published
        run: biosimulations-bigg verify-publication
